//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismicAnalysis.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeismicAnalysis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25
        ///25
        ///22
        ///21
        ///15
        ///15
        ///14
        ///13
        ///11
        ///10
        ///9
        ///5
        ///3
        ///1
        ///27
        ///23
        ///20
        ///17
        ///15
        ///6
        ///3
        ///3
        ///2
        ///1
        ///29
        ///29
        ///23
        ///18
        ///16
        ///14
        ///10
        ///9
        ///4
        ///2
        ///1
        ///31
        ///29
        ///24
        ///24
        ///21
        ///19
        ///19
        ///19
        ///17
        ///16
        ///16
        ///16
        ///16
        ///16
        ///16
        ///16
        ///16
        ///16
        ///16
        ///16
        ///16
        ///16
        ///16
        ///16
        ///16
        ///15
        ///15
        ///15
        ///15
        ///15
        ///15
        ///15
        ///15
        ///15
        ///15
        ///11
        ///8
        ///7
        ///5
        ///4
        ///3
        ///2
        ///29
        ///28
        ///28
        ///27
        ///27
        ///21
        ///19
        ///16
        ///14
        ///13
        ///13
        ///12
        ///12
        ///12
        ///12
        ///11
        ///11
        ///9
        ///1
        ///31
        ///7
        ///6
        ///2
        ///30
        ///26
        ///25
        ///23
        ///22
        ///14
        ///13
        ///11
        ///9
        ///3
        ///29
        ///27
        ///27
        ///25
        ///9
        ///7
        ///6
        ///6
        ///5
        ///5
        ///4
        ///4
        ///4
        ///30
        ///25
        ///22
        ///21
        ///21
        ///21
        ///21
        ///20
        ///20
        ///20
        ///16
        ///13
        ///12
        ///9
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day_1 {
            get {
                return ResourceManager.GetString("Day_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21
        ///18
        ///18
        ///18
        ///18
        ///18
        ///18
        ///18
        ///18
        ///18
        ///18
        ///18
        ///2
        ///23
        ///11
        ///9
        ///3
        ///30
        ///29
        ///23
        ///18
        ///18
        ///14
        ///14
        ///12
        ///9
        ///7
        ///5
        ///3
        ///1
        ///31
        ///31
        ///30
        ///30
        ///30
        ///30
        ///30
        ///30
        ///30
        ///30
        ///30
        ///29
        ///29
        ///28
        ///27
        ///27
        ///27
        ///27
        ///27
        ///26
        ///26
        ///26
        ///26
        ///26
        ///25
        ///24
        ///16
        ///8
        ///7
        ///1
        ///19
        ///3
        ///3
        ///31
        ///31
        ///29
        ///28
        ///28
        ///28
        ///27
        ///26
        ///25
        ///25
        ///25
        ///24
        ///24
        ///24
        ///24
        ///24
        ///24
        ///24
        ///24
        ///24
        ///24
        ///24
        ///24
        ///24
        ///24
        ///30
        ///6
        ///23
        ///19
        ///11
        ///11
        ///31
        ///30
        ///29
        ///28
        ///25
        ///16
        ///8
        ///28
        ///25
        ///25
        ///10
        ///25
        ///16
        ///16
        ///16
        ///15
        ///12
        ///12
        ///11
        ///10
        ///9
        ///3
        ///23
        ///23
        ///22
        ///22
        ///14
        ///10
        ///8
        ///8
        ///7
        ///1
        ///31
        ///28
        ///27
        ///25
        ///25
        ///25
        ///25
        ///2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day_2 {
            get {
                return ResourceManager.GetString("Day_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 58.600
        ///9.000
        ///5.800
        ///10.000
        ///10.000
        ///10.000
        ///4.300
        ///76.200
        ///19.100
        ///23.500
        ///10.000
        ///132.500
        ///20.400
        ///10.000
        ///12.500
        ///16.100
        ///127.700
        ///10.000
        ///24.300
        ///6.600
        ///10.000
        ///38.500
        ///10.000
        ///40.600
        ///14.200
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///42.700
        ///10.000
        ///19.900
        ///9.900
        ///10.000
        ///121.100
        ///11.100
        ///11.900
        ///10.000
        ///8.000
        ///10.000
        ///10.000
        ///49.800
        ///10.000
        ///10.000
        ///13.200
        ///27.100
        ///7.200
        ///11.400
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///11.600
        ///10.000
        ///10.000
        ///9.500
        ///10.000
        ///13.100
        ///10.00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Depth_1 {
            get {
                return ResourceManager.GetString("Depth_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.000
        ///10.000
        ///6.900
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///16.100
        ///8.000
        ///21.900
        ///2.000
        ///26.000
        ///2.800
        ///10.800
        ///9.700
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///19.900
        ///7.600
        ///10.000
        ///8.000
        ///10.000
        ///11.100
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///6.100
        ///10.000
        ///10.000
        ///1.700
        ///10.000
        ///10.000
        ///10.000
        ///264.200
        ///448.500
        ///10.000
        ///3.800
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///10.000
        ///13.400
        ///10.000
        ///11.000
        ///10.000
        ///2.000
        ///7.600
        ///10.000
        ///10.000
        ///5.800
        ///6.600
        ///10.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Depth_2 {
            get {
                return ResourceManager.GetString("Depth_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9994938
        ///9994750
        ///9993944
        ///9993641
        ///9955735
        ///9955732
        ///9955676
        ///9955252
        ///9954433
        ///9954077
        ///9953500
        ///9952422
        ///9951843
        ///9951512
        ///9949368
        ///9948664
        ///9947468
        ///9946739
        ///9946091
        ///9911724
        ///5199624
        ///5199617
        ///5199521
        ///5199389
        ///5199215
        ///5199107
        ///5198564
        ///5198256
        ///5198006
        ///5197801
        ///5197477
        ///5197454
        ///5196975
        ///5196840
        ///5196778
        ///5196707
        ///5196586
        ///5197609
        ///5196225
        ///5196021
        ///5195957
        ///5195939
        ///5195923
        ///5195803
        ///5195796
        ///5195790
        ///5195785
        ///5195783
        ///5195780
        ///5195784
        ///5195764
        ///5195760
        ///5195757
        ///5195752
        ///5195749
        ///5195746
        ///5195743        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRIS_ID_1 {
            get {
                return ResourceManager.GetString("IRIS_ID_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9993574
        ///9992731
        ///9992589
        ///9992583
        ///9992573
        ///9992580
        ///9992568
        ///9992570
        ///9992579
        ///9992576
        ///9992567
        ///9992562
        ///9951333
        ///9948664
        ///9913031
        ///9912421
        ///5199602
        ///5199334
        ///5199212
        ///5198993
        ///5198230
        ///5198214
        ///5198184
        ///5197797
        ///5197766
        ///5197454
        ///5197595
        ///5197062
        ///5196873
        ///5196751
        ///5196707
        ///5196648
        ///5196633
        ///5196622
        ///5196620
        ///5197650
        ///5197649
        ///5196614
        ///5196615
        ///5196613
        ///5196612
        ///5196568
        ///5197636
        ///5196517
        ///5196422
        ///5196403
        ///5196393
        ///5196394
        ///5196387
        ///5196384
        ///5196379
        ///5196376
        ///5196366
        ///5196359
        ///5196292
        ///5196206
        ///5196485        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRIS_ID_2 {
            get {
                return ResourceManager.GetString("IRIS_ID_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.400
        ///36.800
        ///35.510
        ///30.130
        ///39.610
        ///35.110
        ///39.570
        ///35.570
        ///34.440
        ///38.290
        ///38.350
        ///36.420
        ///43.140
        ///35.030
        ///36.590
        ///42.510
        ///36.560
        ///40.020
        ///37.040
        ///38.490
        ///38.130
        ///34.250
        ///36.700
        ///35.490
        ///28.490
        ///34.850
        ///35.440
        ///41.030
        ///41.030
        ///35.180
        ///41.070
        ///42.840
        ///41.850
        ///40.840
        ///36.410
        ///43.220
        ///40.000
        ///38.920
        ///39.800
        ///39.870
        ///39.720
        ///36.060
        ///38.410
        ///37.920
        ///39.810
        ///39.780
        ///39.770
        ///39.740
        ///40.870
        ///39.790
        ///39.770
        ///39.850
        ///39.740
        ///39.790
        ///39.750
        ///39.810
        ///39.730
        ///39.730
        ///39.810
        ///39.770
        ///39.760
        ///39.700
        ///39.720
        ///39.750
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Latitude_1 {
            get {
                return ResourceManager.GetString("Latitude_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42.700
        ///42.670
        ///42.570
        ///42.660
        ///42.750
        ///42.580
        ///42.600
        ///42.600
        ///42.530
        ///42.590
        ///42.600
        ///42.660
        ///42.810
        ///42.510
        ///42.900
        ///43.510
        ///47.060
        ///44.770
        ///42.570
        ///38.250
        ///34.670
        ///34.760
        ///42.940
        ///42.850
        ///42.730
        ///42.840
        ///42.910
        ///35.930
        ///43.030
        ///43.010
        ///43.220
        ///42.750
        ///42.760
        ///42.810
        ///42.840
        ///42.820
        ///43.120
        ///42.770
        ///42.840
        ///42.730
        ///42.850
        ///42.810
        ///40.030
        ///39.310
        ///42.800
        ///42.840
        ///42.930
        ///42.830
        ///42.950
        ///42.800
        ///42.920
        ///42.880
        ///42.930
        ///42.860
        ///43.590
        ///46.400
        ///42.740
        ///42.740
        ///45.230
        ///46.040
        ///42.670
        ///42.880
        ///42.810
        ///36.250
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Latitude_2 {
            get {
                return ResourceManager.GetString("Latitude_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.430
        ///27.640
        ///23.980
        ///31.810
        ///26.160
        ///23.160
        ///26.130
        ///32.390
        ///22.490
        ///21.750
        ///21.750
        ///26.790
        ///25.810
        ///27.010
        ///22.890
        ///18.500
        ///26.920
        ///19.980
        ///28.720
        ///23.520
        ///22.020
        ///25.070
        ///21.580
        ///22.570
        ///34.410
        ///23.250
        ///26.450
        ///22.700
        ///22.710
        ///25.010
        ///22.670
        ///18.470
        ///19.890
        ///34.250
        ///26.360
        ///17.890
        ///19.710
        ///22.110
        ///28.670
        ///20.560
        ///20.560
        ///30.510
        ///21.920
        ///26.960
        ///20.630
        ///20.610
        ///20.630
        ///20.720
        ///30.900
        ///20.660
        ///20.720
        ///20.640
        ///20.710
        ///20.600
        ///20.630
        ///20.610
        ///20.700
        ///20.640
        ///20.590
        ///20.710
        ///20.670
        ///20.700
        ///20.660
        ///20.740
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Longitude_1 {
            get {
                return ResourceManager.GetString("Longitude_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.150
        ///13.210
        ///13.250
        ///13.210
        ///13.280
        ///13.220
        ///13.230
        ///13.170
        ///13.260
        ///13.310
        ///13.240
        ///13.220
        ///12.690
        ///18.500
        ///13.110
        ///16.300
        ///5.430
        ///10.670
        ///13.250
        ///-0.880
        ///6.250
        ///6.240
        ///13.150
        ///13.110
        ///13.130
        ///18.470
        ///13.060
        ///4.010
        ///13.050
        ///13.160
        ///17.890
        ///13.070
        ///13.050
        ///13.100
        ///13.000
        ///13.010
        ///13.120
        ///12.970
        ///13.040
        ///13.160
        ///13.090
        ///13.040
        ///15.790
        ///13.540
        ///13.100
        ///13.050
        ///13.050
        ///13.120
        ///13.020
        ///13.110
        ///13.140
        ///13.000
        ///13.040
        ///13.020
        ///11.060
        ///7.500
        ///13.080
        ///13.190
        ///18.400
        ///6.870
        ///13.160
        ///13.100
        ///13.030
        ///-5.410
        ///13.170 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Longitude_2 {
            get {
                return ResourceManager.GetString("Longitude_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.200
        ///4.000
        ///3.000
        ///4.400
        ///4.300
        ///4.300
        ///4.400
        ///4.300
        ///4.500
        ///4.500
        ///4.900
        ///4.300
        ///4.200
        ///4.900
        ///4.900
        ///4.300
        ///5.400
        ///4.300
        ///4.200
        ///4.000
        ///5.000
        ///4.500
        ///4.500
        ///4.300
        ///4.400
        ///4.500
        ///4.200
        ///4.900
        ///4.200
        ///4.000
        ///4.800
        ///4.400
        ///4.300
        ///4.300
        ///4.400
        ///4.300
        ///4.400
        ///4.200
        ///4.100
        ///4.000
        ///4.500
        ///4.700
        ///4.100
        ///4.400
        ///4.100
        ///4.600
        ///4.500
        ///4.100
        ///4.300
        ///4.300
        ///4.500
        ///4.400
        ///4.500
        ///5.100
        ///5.000
        ///4.800
        ///4.900
        ///4.200
        ///5.200
        ///5.000
        ///4.400
        ///4.300
        ///4.300
        ///4.300
        ///4.400
        ///4.600
        ///5.500
        ///5.300
        ///4.500
        ///4.100
        ///4.700
        ///4.000
        ///3.900
        ///3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Magnitude_1 {
            get {
                return ResourceManager.GetString("Magnitude_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.100
        ///4.700
        ///5.200
        ///4.100
        ///4.700
        ///4.300
        ///5.600
        ///4.500
        ///4.600
        ///4.700
        ///5.700
        ///5.300
        ///4.100
        ///4.300
        ///4.200
        ///4.400
        ///4.100
        ///3.700
        ///4.500
        ///3.000
        ///4.900
        ///5.300
        ///4.100
        ///4.200
        ///4.600
        ///4.400
        ///4.300
        ///4.200
        ///5.000
        ///4.900
        ///4.300
        ///4.300
        ///4.300
        ///4.600
        ///4.700
        ///4.500
        ///4.600
        ///4.700
        ///4.000
        ///4.300
        ///6.600
        ///4.500
        ///4.400
        ///5.800
        ///4.200
        ///4.300
        ///4.200
        ///4.500
        ///4.200
        ///4.000
        ///4.900
        ///4.100
        ///6.100
        ///5.500
        ///4.200
        ///4.400
        ///4.300
        ///4.300
        ///3.900
        ///3.800
        ///4.100
        ///4.500
        ///4.300
        ///3.800
        ///4.100
        ///3.500
        ///4.300
        ///4.600
        ///4.300
        ///4.200
        ///4.700
        ///4.300
        ///4.700
        ///4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Magnitude_2 {
            get {
                return ResourceManager.GetString("Magnitude_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January 
        ///January 
        ///January 
        ///January 
        ///January 
        ///January 
        ///January 
        ///January 
        ///January 
        ///January 
        ///January 
        ///January 
        ///January 
        ///January 
        ///December 
        ///December 
        ///December 
        ///December 
        ///December 
        ///December 
        ///December 
        ///December 
        ///December 
        ///December 
        ///November
        ///November
        ///November
        ///November
        ///November
        ///November
        ///November
        ///November
        ///November
        ///November
        ///November
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Month_1 {
            get {
                return ResourceManager.GetString("Month_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January 
        ///January 
        ///January 
        ///January 
        ///January 
        ///January 
        ///January 
        ///January 
        ///January 
        ///January 
        ///January 
        ///January 
        ///January 
        ///December 
        ///December 
        ///December 
        ///December 
        ///November
        ///November
        ///November
        ///November
        ///November
        ///November
        ///November
        ///November
        ///November
        ///November
        ///November
        ///November
        ///November
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///October
        ///O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Month_2 {
            get {
                return ResourceManager.GetString("Month_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRETE, GREECE
        ///DODECANESE ISLANDS, GREECE
        ///CRETE, GREECE
        ///EGYPT
        ///TURKEY
        ///CRETE, GREECE
        ///TURKEY
        ///CYPRUS REGION
        ///CENTRAL MEDITERRANEAN SEA
        ///GREECE
        ///GREECE
        ///DODECANESE ISLANDS, GREECE
        ///BULGARIA
        ///DODECANESE ISLANDS, GREECE
        ///SOUTHERN GREECE
        ///NORTHWESTERN BALKAN REGION
        ///DODECANESE ISLANDS, GREECE
        ///ALBANIA
        ///TURKEY
        ///GREECE
        ///GREECE
        ///CRETE, GREECE
        ///SOUTHERN GREECE
        ///CENTRAL MEDITERRANEAN SEA
        ///EGYPT
        ///CRETE
        ///CRETE
        ///NORTHWESTERN BALKAN REGION
        ///NORTHWESTERN BALKAN REGION
        ///CRETE
        ///NORTHWESTERN BALKAN REGION
        ///NORTHWESTERN BA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Region_1 {
            get {
                return ResourceManager.GetString("Region_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CENTRAL ITALY
        ///CENTRAL ITALY
        ///CENTRAL ITALY
        ///CENTRAL ITALY
        ///CENTRAL ITALY
        ///CENTRAL ITALY
        ///CENTRAL ITALY
        ///CENTRAL ITALY
        ///CENTRAL ITALY
        ///CENTRAL ITALY
        ///CENTRAL ITALY
        ///CENTRAL ITALY
        ///CENTRAL ITALY
        ///NORTHWESTERN BALKAN REGION
        ///CENTRAL ITALY
        ///NORTHWESTERN BALKAN REGION
        ///FRANCE
        ///NORTHERN ITALY
        ///CENTRAL ITALY
        ///SPAIN
        ///NORTHERN ALGERIA
        ///NORTHERN ALGERIA
        ///CENTRAL ITALY
        ///CENTRAL ITALY
        ///CENTRAL ITALY
        ///NORTHWESTERN BALKAN REGION
        ///CENTRAL ITALY
        ///NORTHERN ALGERIA
        ///CENTRAL ITALY
        ///CENTRAL ITALY
        ///NORTHWESTERN BALKAN REGION
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Region_2 {
            get {
                return ResourceManager.GetString("Region_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18:50:52
        ///01:19:33
        ///09:22:19
        ///16:54:22
        ///04:03:21
        ///03:37:19
        ///22:38:59
        ///21:43:32
        ///15:50:29
        ///12:44:54
        ///09:53:17
        ///14:05:03
        ///22:02:33
        ///13:04:02
        ///19:31:05
        ///23:39:25
        ///06:03:44
        ///10:39:36
        ///16:44:00
        ///17:14:40
        ///21:04:35
        ///13:58:15
        ///11:46:04
        ///05:36:26
        ///17:01:12
        ///00:19:28
        ///00:01:27
        ///23:22:48
        ///09:15:15
        ///02:34:40
        ///12:12:44
        ///15:58:44
        ///05:08:53
        ///11:57:44
        ///18:58:20
        ///09:38:13
        ///20:15:28
        ///22:09:56
        ///21:04:47
        ///01:54:59
        ///21:23:56
        ///12:18:46
        ///00:08:45
        ///01:30:30
        ///23:21:33
        ///19:01:40
        ///16:44:04
        ///15:47:54
        ///14:11:25
        ///13:18:01
        ///08:40:20
        ///05 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Time_1 {
            get {
                return ResourceManager.GetString("Time_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 09:35:57
        ///15:16:12
        ///13:33:37
        ///12:01:41
        ///11:07:39
        ///10:39:24
        ///10:25:25
        ///10:24:16
        ///10:16:37
        ///10:15:32
        ///10:14:11
        ///09:25:41
        ///03:36:14
        ///23:39:25
        ///12:54:52
        ///12:57:01
        ///09:01:43
        ///05:52:55
        ///16:14:03
        ///15:28:28
        ///12:08:19
        ///07:42:22
        ///19:49:52
        ///01:33:44
        ///14:43:35
        ///15:58:44
        ///18:56:17
        ///20:43:24
        ///00:35:01
        ///07:56:40
        ///09:38:13
        ///03:27:41
        ///18:21:09
        ///13:34:55
        ///12:07:02
        ///11:58:18
        ///11:21:11
        ///08:36:01
        ///07:34:48
        ///07:13:06
        ///06:40:19
        ///16:24:33
        ///11:58:06
        ///20:02:48
        ///17:22:24
        ///08:21:45
        ///03:50:24
        ///03:19:27
        ///00:21:31
        ///23:52:31
        ///21:42:03
        ///21 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Time_2 {
            get {
                return ResourceManager.GetString("Time_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1485370252
        ///1485307173
        ///1485076939
        ///1485017662
        ///1484453001
        ///1484451439
        ///1484433539
        ///1484343812
        ///1484149829
        ///1484052294
        ///1483955597
        ///1483625103
        ///1483480953
        ///1483275842
        ///1482867065
        ///1482536365
        ///1482213824
        ///1481971176
        ///1481820240
        ///1481044480
        ///1480799075
        ///1480773495
        ///1480679164
        ///1480570586
        ///1480438872
        ///1480378768
        ///1479859287
        ///1479511368
        ///1479287715
        ///1479090880
        ///1478779964
        ///1478707124
        ///1478236133
        ///1478087864
        ///1478026700
        ///1477906693
        ///1477772128
        ///1477346996
        ///1477343087
        ///1477014899
        ///1476912236
        ///1476879526
        ///14768357 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Timestamp_1 {
            get {
                return ResourceManager.GetString("Timestamp_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1484991357
        ///1484752572
        ///1484746417
        ///1484740901
        ///1484737659
        ///1484735964
        ///1484735125
        ///1484735056
        ///1484734597
        ///1484734532
        ///1484734451
        ///1484731541
        ///1483328174
        ///1482536365
        ///1481460892
        ///1481288221
        ///1480755703
        ///1480485175
        ///1480436043
        ///1479914908
        ///1479470899
        ///1479454942
        ///1479152992
        ///1479087224
        ///1478961815
        ///1478707124
        ///1478544977
        ///1478378604
        ///1478133301
        ///1477987000
        ///1477906693
        ///1477884461
        ///1477851669
        ///1477834495
        ///1477829222
        ///1477828698
        ///1477826471
        ///1477816561
        ///1477812888
        ///1477811586
        ///1477809619
        ///1477758273
        ///14777422 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Timestamp_2 {
            get {
                return ResourceManager.GetString("Timestamp_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2017
        ///2017
        ///2017
        ///2017
        ///2017
        ///2017
        ///2017
        ///2017
        ///2017
        ///2017
        ///2017
        ///2017
        ///2017
        ///2017
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Year_1 {
            get {
                return ResourceManager.GetString("Year_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2017
        ///2017
        ///2017
        ///2017
        ///2017
        ///2017
        ///2017
        ///2017
        ///2017
        ///2017
        ///2017
        ///2017
        ///2017
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///2016
        ///20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Year_2 {
            get {
                return ResourceManager.GetString("Year_2", resourceCulture);
            }
        }
    }
}
